#!/bin/bash

FILE=`basename $0`
 
# Screen setup
SCREENRC="$HOME/.screenrc"
echo "Looking for '$SCREENRC' ... "
if [ ! -e "$SCREENRC" ]; then
  echo "Couldn't find it, setting it up."
  touch "$SCREENRC"
  echo -e "## This file was auto-generated by '$FILE'" >> $SCREENRC
  echo -e "# Change the escape key from 'a' to 'z'\nescape ^Zz" >> $SCREENRC 
  echo -e "# Autodetach from a session on hangup instead of terminating\nautodetach on" >> $SCREENRC
  echo -e "# Turn off that annoying splash screen\nstartup_message off" >> $SCREENRC
  echo -e "# Use a 30,000 line scrollback buffer by default\ndefscrollback 30000" >> $SCREENRC
  echo -e "# Set and style captions\ncaption always '%{= kw}%-w%{+bs bW}%n-%t%{-}%+w %-= @%H - %D, %M %d %Y - %c:%s'" >> $SCREENRC
  echo "All done!"
else
  echo "Found it! Skipping setup."
fi

# Vim setup
VIMRC="$HOME/.vimrc"
echo "Looking for '$VIMRC' ... "
if [ ! -e "$VIMRC" ]; then
  echo "Couldn't find it, setting it up."
  touch "$VIMRC"
  echo -e "\"\" This file was auto-generated by '$FILE'" >> $VIMRC
  echo -e "\" Use four spaces instead of tabs\nset tabstop=4 shiftwidth=4 expandtab" >> $VIMRC
  echo "All done!"
else
  echo "Found it! Skipping setup."
fi

# Bash setup
BASHRC="$HOME/.bashrc"

