trigger:
  branches:
    include:
      - main
  tags:
    include: ['*']
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    buildSteps:
      - script: yarn install --frozen-lockfile
        displayName: Install dependencies

      - script: yarn test
        displayName: Test

      - script: yarn run vscode:prepublish
        displayName: Compile
