source 'https://rubygems.org'

ruby '2.2.2'

gem 'rails', '~> 4.2'
gem 'haml-rails', '~> 0.4'
gem 'therubyracer', '~> 0.12'
gem 'jquery-rails'
gem 'turbolinks'
gem 'puma', '~> 2.12'

group :assets do
  gem 'sass-rails', '~> 4.0', require: 'sass'
  gem 'uglifier', '~> 1.3'
end

group :development, :test do
  gem 'sqlite3', '~> 1.3'
  gem 'spring'
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
end

